import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/context/userContext";
import { TravelProvider } from "@/context/travelContext";

export const metadata: Metadata = {
  title: "Sí, Voy | Turismo Accesible",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <UserProvider>
        <TravelProvider>
            <Navbar />
            {children}
           <Footer />
        </TravelProvider>
      </UserProvider>
      </body>
    </html>
  );
};