import NavbarComponent from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Metadata } from "next";
import "./globals.css";

import { TravelProvider } from "@/context/travelContext";
import { UserProvider } from "@/context/userContext";
import SessionWrapper from "@/components/SessionWrapper";


export const metadata: Metadata = {
  title: "Sí, Voy | Turismo Accesible",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          <UserProvider>
           <TravelProvider>
            <NavbarComponent />
              <div className="lg:ml-16 lg:mr-16">
                {children}
              </div>
           <Footer />
          </TravelProvider>
         </UserProvider>
       </SessionWrapper>
      </body>
    </html>
  );
};