import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "",
//   description: "Generated by create next app",
// };

// para esto de arriba parece que faltan dependencias

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        // className={inter.className}
        >
            <Navbar />
            {children}
           <Footer />
      </body>
    </html>
  );
};